Remove the executable bit from all the .py files.
canonical/operator pull request #1059
Opened 2023-11-08 11:48 UTC by jameinel

None of these are run as scripts, and aren't meant to be executable.

(Note that src/charm.py would be executable, but that is the user script, not the ops internal libraries)

2023-11-08 13:52 UTC, benhoyt commented
Thanks! Additionally see below (though if you don't get a chance to do it, one of us can do it before we merge).

These should also have their x bit removed:

```
-rwxrwxr-x  1 ben ben  30676 Oct 12 06:36 test_charm.py*
-rwxrwxr-x  1 ben ben  68893 Oct  5 05:39 test_framework.py*
-rwxrwxr-x  1 ben ben   5253 Oct  5 05:39 test_helpers.py*
-rwxrwxr-x  1 ben ben   7990 Oct  5 05:39 test_jujuversion.py*
-rwxrwxr-x  1 ben ben  51001 Oct  5 05:39 test_main.py*
-rwxrwxr-x  1 ben ben 145152 Oct 26 22:10 test_model.py*
-rwxrwxr-x  1 ben ben  15809 Oct  5 05:39 test_storage.py*
```

And these should have their hash-bang lines removed, as we don't (and probably can't in most cases) run tests this way:

```
test/test_log.py
1:#!/usr/bin/python3

test/test_real_pebble.py
1:#!/usr/bin/python3

test/test_pebble.py
1:#!/usr/bin/python3

test/test_model.py
1:#!/usr/bin/python3
```

2023-11-08 13:52 UTC, benhoyt requested changes
Thanks! See above comment -- but if you don't get to this, no problem! We'll do it before merging.

2023-11-09 08:20 UTC, tonyandrewmeyer approved these changes

2023-11-09 08:21 UTC, tonyandrewmeyer commented
> These should also have their x bit removed:

Done.

> And these should have their hash-bang lines removed, as we don't (and probably can't in most cases) run tests this way:

Done.

2023-11-09 08:29 UTC, benhoyt approved these changes

2023-11-09 08:30 UTC, merged