add_relation_unit(... data=Mapping[str,str])
canonical/operator pull request #1202
Opened 2024-04-25 10:25 UTC by PietroPasotti

Now that we have `add_relation` and you can pass app and unit data straight away, why don't we also extend `add_relation_unit` with a similar API?

2024-04-25 21:41 UTC, tonyandrewmeyer commented
> Now that we have `add_relation` and you can pass app and unit data straight away, why don't we also extend `add_relation_unit` with a similar API?

I'm not 100% convinced that adjusting `add_relation` was the right thing to do (for example, it makes `add_relation` potentially emit more than once and that has charm-object-reuse issues). However, the cat is well out of the bag with that, so this makes sense to me.

I looked through the [issue](https://github.com/canonical/operator/issues/992) and PR that added this to `add_relation`, and I couldn't find any discussion of whether this should be done for `add_relation_unit` as well for consistency, so I'm guessing it wasn't considered and decided against.

So adding this is a +1 from me, what do you think @canonical/charm-tech ?

2024-04-25 22:01 UTC, benhoyt requested changes
Yep, I agree with your reasoning @tonyandrewmeyer -- this is a reasonable addition for consistency with the changes to `add_relation`, and I think it was just missed at the time.

Couple of suggestions for docs and tests.

2024-04-26 04:47 UTC, tonyandrewmeyer commented
> So adding this is a +1 from me, what do you think @canonical/charm-tech ?

Out of curiosity, @PietroPasotti, what was your motivation for this? I would assume that you're not generally writing many Harness tests - is `add_relation_unit` followed by `update_relation_data` something you're seeing regularly in some set of charms?

2024-04-26 06:19 UTC, PietroPasotti commented
> Out of curiosity, @PietroPasotti, what was your motivation for this? I would assume that you're not generally writing many Harness tests - is `add_relation_unit` followed by `update_relation_data` something you're seeing regularly in some set of charms?

I was adding a harness test to an old suite and it suddenly felt odd not to have it :)

2024-04-26 22:20 UTC, benhoyt commented
Tony and I discussed this yesterday, and we're both not opposed but a bit ambivalent on the feature itself. However, we discussed that we'd rather not squeeze new features into Harness at this point (even if small features), but rather start pointing people to Scenario, the longer-term focus. I know it's a tad early as the new Scenario 7.0 "final" API hasn't shipped, but I don't think we should be adding new little helpers to Harness at this point.

2024-04-26 22:20 UTC, closed without merging