Allow the `other` argument to `RelatationDataContent.update(...)` to be optional
canonical/operator pull request #1226
Opened 2024-05-22 19:33 UTC by addyess

2024-05-22 19:35 UTC, addyess commented
@tonyandrewmeyer and @benhoyt  I appreciate your speedy review as this likely break a few releases queued up for this week.

2024-05-23 01:35 UTC, dimaqq commented
The change makes sense, I believe Tony volunteered to tests for this.

2024-05-23 02:00 UTC, dimaqq approved these changes

2024-05-23 02:00 UTC, dimaqq commented on ops/model.py
> +    def update(self, other: typing.Any = (), /, **kwargs: str):
**TIL** that typeshed doesn't even define `dict.update`

https://github.com/python/typeshed/blob/main/stdlib/builtins.pyi#L1029

So, all good here!

2024-05-23 02:00 UTC, dimaqq commented on test/test_model.py
> +            rel.data[harness.model.app].update(foo='baz')
Let's cover some flavour of `.update(iterable)` while we're at it.

2024-05-23 02:40 UTC, dimaqq approved these changes
Super-minor/bikeshedding: I suppose the test could be more concise (either parametrised of performing all 3 updates on the same object/within same test).

Happy to have this fix!

2024-05-23 02:49 UTC, tonyandrewmeyer commented
> Super-minor/bikeshedding: I suppose the test could be more concise (either parametrised of performing all 3 updates on the same object/within same test).

Fair point. I have never really been in the habit of using `unittest.subTest` for this, but now that we are (very nearly) switched over to pytest, using `pytest.mark.parametrize` would be cleaner.

2024-05-23 03:05 UTC, addyess commented
Wow, thanks for the improved solution @dimaqq!

2024-05-23 03:21 UTC, dimaqq commented
@tonyandrewmeyer deserves the credit. I've only reviewed the PR 🙇🏻

2024-05-23 13:08 UTC, addyess commented
> @tonyandrewmeyer deserves the credit. I've only reviewed the PR 🙇🏻

Sorry, it was late and i was blurry-eyed 👀 .  Thanks so much @tonyandrewmeyer!

2024-05-23 15:23 UTC, addyess commented
@IronCore864 Thanks so much also for offering a review

2024-05-23 23:01 UTC, benhoyt requested changes
Fix looks good, thanks @addyess. I agree that the tests have a bit too much duplication, parametrization seems like a good idea here.

2024-05-24 00:41 UTC, benhoyt approved these changes
Much nicer, thanks

2024-05-24 00:42 UTC, merged