ci: run tests on Py 3.13 as well
canonical/operator pull request #1315
Opened 2024-08-15 00:53 UTC by dimaqq

Python 3.13 has reached rc1, this PR adds it to the test matrix.

Note: not using free-threaded builds at this point due to  https://github.com/actions/setup-python/issues/771 (not like we'd expect any difference, frankly)

2024-08-15 23:51 UTC, IronCore864 approved these changes

2024-08-16 02:19 UTC, benhoyt requested changes
Per discussion, we're going to add 3.12 to the places it's missing, but leave 3.13 for now. When 3.13 is out, we'll add it to the `pip install` block but not for running our tests.

2024-08-16 05:46 UTC, dimaqq commented
Aside: why do test one artefact, but not the other?
- `dist/ops-<version>.tar.gz` is tested
- `dist/ops-<version>-py3-none-any.whl` is not tested

Is it because `charmcraft pack` will use .gz and that's all we care about?

2024-08-16 05:46 UTC, dimaqq commented
Updated Python versions per review.

2024-08-16 09:56 UTC, tonyandrewmeyer commented
> Aside: why do test one artefact, but not the other?
> 
> * `dist/ops-<version>.tar.gz` is tested
> * `dist/ops-<version>-py3-none-any.whl` is not tested
> 
> Is it because `charmcraft pack` will use .gz and that's all we care about?
> 
> Full disclosure: I believe that the packages are equivalent for install purpose, even though the content is not equivalent: 97 files in a tarball, 26 files in a zip/whl. The differences are our tests, tox.ini, setup.cfg and pyproject.toml.

Yeah, I think that's the reason why: if we broke installing, it's hard to see how we would break wheel and not sdist or the other way around. The packaging tools could, but probably not something we do. So if there's no point checking both, then we might as well check the one that will be used when packing.

2024-08-18 21:30 UTC, benhoyt approved these changes
LGTM, thanks!

2024-08-19 00:16 UTC, merged