chore: update charm pins
canonical/operator pull request #1442
Opened 2024-10-25 00:24 UTC by benhoyt

This is an automated PR to update pins of the external repositories that the operator framework is tested against

2024-10-25 04:46 UTC, tonyandrewmeyer requested changes
One of us needs to again look into whether we can re-enable the full set. I'll try to find time this afternoon.

2024-10-25 08:24 UTC, tonyandrewmeyer commented on .github/workflows/observability-charm-tests.yaml
> +            commit: fe233592f9324a6cf4aa9dbc71577ee170cf9eb3  # rev138 2024-10-18T12:11:02Z
```suggestion
          fe233592f9324a6cf4aa9dbc71577ee170cf9eb3  # rev138 2024-10-18T12:11:02Z
          # Waiting for an upstream PR:
          # https://github.com/canonical/prometheus-k8s-operator/pull/639
          #- charm-repo: canonical/prometheus-k8s-operator
          #  commit: 7518ec8343941ca91248614fd8f2d50fdd9e068c  # rev135 2024-09-06T12:10:02Z
          - charm-repo: canonical/grafana-k8s-operator
            commit: 07a52a65f272e115ab786f30cdb3b53be6b34bb7
```

Looks like grafana-k8s is fixed, but promtheus-k8s is still not.

2024-10-25 08:29 UTC, tonyandrewmeyer approved these changes

2024-10-26 10:53 UTC, dimaqq approved these changes

2024-10-26 15:17 UTC, merged