Set Relation.app from JUJU_REMOTE_APP directly to avoid KeyError
canonical/operator pull request #475
Opened 2021-02-10 04:42 UTC by benhoyt

This is happening because we were setting `Relation.app` from the app of the first unit, but if an event was fired before any units had started up (this happens on `relation-created`, for example), the `app` field was None and this caused a `KeyError` later when charms did things like `event.relation.data[event.app]`.

The code will still fall back to the current method (first app of the units) if `JUJU_REMOTE_APP` is not set, which should only happen on Juju prior to 2.7, when `JUJU_REMOTE_APP` was added.

This is https://github.com/canonical/operator/issues/175 and manifests itself as issues like https://bugs.launchpad.net/juju/+bug/1914415

NOTE: I'm going to add a couple more tests, but this is basically what I have in mind for the fix. I've also tested locally using the repro steps on that LP bug 1914415 (fails before, works after).

2021-02-10 22:30 UTC, jameinel requested changes
We discussed this in person, but it isn't complete as is.
The problem is that it assumes JUJU_REMOTE_APP is valid for all relations, while it is only valid for the current JUJU_RELATION_ID.
However, if we tracked those two pieces, we probably have a reasonable fix for #175 that would be backwards compatible with juju 2.7 and 2.8. And while it doesn't solve the overall modeling problem it does, at least, fix a common error case.

2021-02-12 14:00 UTC, jameinel requested changes
I think this is certainly going in the right direction. A few small changes.
We also are missing the direct tests of the _ModelBackend (when the env var is set, when it is set but matches a different relation_id, etc)

2021-02-15 01:53 UTC, benhoyt commented on ops/model.py
> +                 event_relation_id=None):
Fair enough. Yeah, I just moved the `os.environ` fetching into `relation_remote_app_name()` itself.

2021-02-15 01:53 UTC, benhoyt commented on ops/model.py
> +        if relation_id == self.event_relation_id:
See above -- done.

2021-02-15 01:54 UTC, benhoyt commented on ops/model.py
> +                self.app = cache.get(Application, app_name)
This is a nice refactoring -- I like it and agree with these reasons. Done. It definitely reduced the test churn, and will reduce calls to `relation-list --app` in future.

2021-02-15 01:54 UTC, benhoyt commented on ops/model.py
> +                    # JUJU_REMOTE_APP is not set (pre Juju 2.7) or this is not
Got it. And updated the comment.

2021-02-15 01:56 UTC, benhoyt commented on ops/testing.py
> +    def relation_remote_app(self, relation_id):
I didn't add a type annotation here originally just to be consistent with the surrounding code (which doesn't have any). Added.

That said, I hope to enable `mypy` on the project in general. It's not ideal to have type annotations that aren't checked (they provide documentation, but we might as well test our documentation so it doesn't get out of sync with reality).

2021-02-15 01:56 UTC, benhoyt commented on test/test_testing.py
>          # If we check again, they are still there, but now we reset it
Good. Added this for both the testing version and the real version.

2021-02-15 04:25 UTC, benhoyt commented
@jameinel Ian pointed out that `relation-list --app` might exist already, and sure enough, it does! I've updated the code/tests to use that.

2021-02-16 18:36 UTC, jameinel requested changes

2021-02-16 20:09 UTC, benhoyt commented on ops/model.py
> +        if 'JUJU_RELATION_ID' not in os.environ:
Very good point -- fixed so it uses `relation-list --app` as a fallback in all cases (either env var unset, or `JUJU_RELATION_ID` not this relation).

2021-02-16 20:10 UTC, benhoyt commented on ops/model.py
> +            if 'relation not found' in str(e):
I've added a `_is_relation_not_found` helper to unify and avoid typos.

Regarding returning `None` here -- it seemed right for this function (and is documented and used as such). Given that it's an internal function, I think it's fine, and we can always iterate later if we want to.

2021-02-16 20:11 UTC, benhoyt commented on test/test_model.py
> +        self.assertEqual(self.backend.relation_remote_app_name(5), 'remoteapp1')
Good call -- added.

2021-02-16 20:11 UTC, benhoyt commented on test/test_model.py
> +        fake_script(self, 'relation-list', r"""
Fair -- I've separated into `_env`, `_script_success`, and `_script_errors` (and added the couple of missing tests).

2021-02-16 20:19 UTC, jameinel approved these changes
Thanks for the updates

2021-02-17 01:00 UTC, hpidcock approved these changes
LGTM thank-you

2021-02-17 01:16 UTC, merged