Expose 'limit' in RelationMeta
canonical/operator pull request #552
Opened 2021-06-16 08:01 UTC by mmanciop

The [metadata.yaml spec](https://discourse.charmhub.io/t/charm-metadata-v2/3674) allows to limit the cardinality of relations using the `limit` keyword, e.g., when we want _up to_ one relation in the model using the `mongodb-datasource` interface.

This PR adds support to `limit` in the `RelationMeta` class, which is currently not accessible at runtime by charms.

2021-06-16 10:57 UTC, rbarry82 commented on test/test_charm.py
> +    def test_relations_meta_limit_type_validation(self):
Duplicate test.

2021-06-16 10:57 UTC, rbarry82 commented on ops/charm.py
> +    DEFAULT_SCOPE = VALID_SCOPES[0]
This is always dangerous. `DEFAULT_SCOPE` will be set a single time, at class evaluation time. It's not necessarily a big deal here, but every instance of the class will have the same values.

2021-06-16 10:57 UTC, rbarry82 commented on ops/charm.py
> +            raise TypeError("scope should be one of {}; not '{}'".format(valid_scopes, scope))
This is confusing to read:

    raise TypeError("scope should be one of '{}'; not '{}'".format(
                    ', '.join(VALID_SCOPES), scope))

2021-06-16 10:57 UTC, rbarry82 commented on ops/charm.py
> +        self.scope = scope or RelationMeta.DEFAULT_SCOPE
`self.scope = scope or DEFAULT_SCOPE`

2021-06-16 10:57 UTC, rbarry82 commented on ops/charm.py
> +            self.limit = int(limit)
This will never be reached

2021-06-16 10:57 UTC, rbarry82 commented on ops/charm.py
> +        if limit is not None:
`if limit and type(limit) is not int:`

2021-06-16 10:59 UTC, rbarry82 requested changes

2021-06-16 10:59 UTC, rbarry82 commented on ops/charm.py
> +        if limit is not None:
`if limit and type(limit) is not int:`

2021-06-16 19:39 UTC, rbarry82 approved these changes
LGTM

2021-06-23 15:54 UTC, jameinel approved these changes
Thanks. It does mean limit may be None or an integer, but I think that is well conveyed with the docstring "Optional ..."

And setting limit to 0 if it wasn't defined would be confusing, since "count > limit" would return true but 0 would actually mean infinite. So they already need a second if clause, and `if limit and count > limit` is a good way to express it.

2021-06-23 15:54 UTC, jameinel commented on ops/charm.py
> +        if self.limit and type(self.limit) is not int:
Isn't this better expressed as:
```
if self.limit and not isinstance(self.limit, int):
```

2021-06-23 16:05 UTC, balbirthomas approved these changes

2021-06-25 14:55 UTC, mmanciop commented on ops/charm.py
> +        self.limit = raw.get('limit')
Yeah I understand this to be the spec: https://discourse.charmhub.io/t/charm-metadata-v2/3674

2021-06-25 15:09 UTC, mmanciop commented on ops/charm.py
> +        if self.limit and type(self.limit) is not int:
Done :-)

2021-07-08 15:47 UTC, merged