Remove triple backticks from ops.model docs since Sphinx doesn't like them
canonical/operator pull request #600
Opened 2021-09-02 21:41 UTC by rbarry82

As the header, really.

Closes #599

2021-09-02 22:05 UTC, benhoyt requested changes

2021-09-02 22:05 UTC, benhoyt commented on ops/model.py
>          Example:
This still doesn't render as a monospaced code block in ReST. Use the `::` syntax, so `Example::` followed by a blank line:

```suggestion
        Example::
        
```

2021-09-02 22:05 UTC, benhoyt commented on ops/model.py
>          Example:
There's another instance of this (and triple back ticks) below.

In general, the docs need a bit of a syntax go-over, but oh well, another day...

2021-09-02 22:05 UTC, benhoyt commented on ops/model.py
>          Example:
BTW, you can build the docs with `./build_docs` (assuming you're in a venv with `requirements-dev.txt` libraries installed).

2021-09-02 22:10 UTC, rbarry82 commented
Fixed/updated. That make target is super useful. Thanks @benhoyt !

2021-09-02 22:25 UTC, benhoyt commented on ops/model.py
> +        Example::
I believe you need a blank line after the `Example::` line for it to render as a monospaced code block.

2021-09-03 03:20 UTC, benhoyt approved these changes

2021-09-03 13:46 UTC, dstathis approved these changes
:+1:

2021-09-03 16:40 UTC, merged