Parse revision|version into CharmMeta
canonical/operator pull request #692
Opened 2022-02-15 03:18 UTC by rbarry82

Operator Framework does not currently do anything with `version`
(which no longer appears to be automatically generated by
`charmcraft` anyway) or `revision`, which is always present when
Juju deploys, even if it's `0` for a locally-built charm.

Expose these in `CharmMeta` so authors can use it to
`set_workload_version` based on `charm.meta` information if desired,
or otherwise perform labeling/checking on metrics labels or other
data.

2022-02-15 03:19 UTC, rbarry82 commented
@jnsgruk  @facundobatista @jameinel @johnsca @pengale I'm guessing there's some historical reason why we do _not_ expose them, and if there is, we can close this, but at least we'd have a more recent explanation for the rationale.

2022-02-15 17:15 UTC, facundobatista commented
Hello! Don't remember anything specific for this :/.

2022-02-15 17:37 UTC, pengale requested changes
This is a need, but I don't believe that the PR, as written, will reliably address the need. (See comment.)

2022-02-15 18:33 UTC, rbarry82 commented
> I believe that the issue here is that the versions don't live in the metadata.yaml. The charm revision is something that is generated when you publish a charm. It's accessible to Juju at deploy time, but it isn't accessible to the charm.

Well, it is -- at runtime. In k8s charms, it's actually created in the same path as the charm itself is unpacked. 

It certainly appears to be generated if it doesn't exist when you _deploy_ a charm also -- `charmcraft pack ... && juju deploy ./foo.charm` still gives a `revision` file, even if the value is `0`, which could be worked address in OF.

> Exposing the version of the actual software in the workload is often useful, but that's not in the charm's metadata. In order to expose the actual workload software version, you'd need to figure out how to get at that info for the specific workload, then set that via the usual helper tools for status.

There are different cases here. Whether it's in the metadata, as a property on `CharmBase`, or anywhere else, the goal is not necessarily simply to `set_workload_version()` (and doing so automatically isn't part of this PR at all, since it's an undiscussed behavior change), but also to be able to use it in Prometheus labels, logs, or elsewhere.

If I pick an arbitrary charm, Cassandra's metrics exporting are a separate Juju resource which is injected into the workload container -- the version of the metrics exporter is not tied to the workload version, but to the charm version. Exposing the version/revision would provide an easy way to say "these metrics are coming from `charm_revision=1234`".

Similar use cases are present for Grafana dashboards (and were also in the reactive version), alerting rules, and likely a lot of use cases outside of observability, those are just the ones I can rattle off. A Grafana dashboard for nginx, for example, would be included in the nginx charm, not the workload.

As of now, we have centralized way to say "tell me revision/version of the charm that this came from" and include it in file metadata/relation data/other, which is valuable for bug reports.

> We could possibly write a "guess my version!" library that automated some of this. I'll add it to our list of ideas. But I don't believe that this PR reflects production code.

Part of the reason that this was a "blind" PR is that there isn't a consistent story around this. [`charmcraft` does keep a version file if present](https://github.com/canonical/charmcraft/blob/677b399f5c73501bccbd41421ecc13be708019cb/charmcraft/commands/build.py#L54), but it's up to charm authors to know they need to set this, because [`charmcraft` also ignores all source control paths as well as `revision`](https://github.com/canonical/charmcraft/blob/b8ef3a45ef472730a099ee21d1aa1abe5c0a35f4/charmcraft/jujuignore.py#L221).

[`charm` (as much as it's being supplanted by `charmcraft`)](https://github.com/juju/charm/blob/d3c79ce32e778361b8338f22b10fe6cf66c14c1a/charmdir.go#L238) did try to generate `version` from VCS, though, which presumably got used by Juju.

OF does nothing with this whatsoever.

At least from source diving in repos, it appears that the following things are true:
* `version` not being automatically generated from VCS is a behavior change in `charmcraft`, and I imagine there is a historical reason for this, but I'm not sure what it is
* `juju deploy` _always_ creates a `revision` -- `0` for locally build charms, otherwise what comes from charmhub. This is a reliable feature of every deployed k8s charm I've checked, and the PR only conditionally checks the file anyway
* Considering the historical automatic generation of `version` and `charmcraft` keeping this in the bundle, injecting it into the metadata would involve PRs to `charm`, `charmcraft`, or both, and a change in a PR here to expose it
* `charmcraft` cannot know the revision which will be set in the store, so any modification of `revision` for uploaded charms in the YAML would need to happen there.
* In any case, OF does not do anything with this information by default, and expects Charm authors to look for them if they need them. Charm authors should also be aware of the differences in `version` generation between `charm` and `charmcraft` to determine whether `version` is present at all.

With these in mind, it's difficult to see somewhere for this to be checked in a reasonable timeframe (assuming that whatever changes to metadata above even made it through), and the code involved hardly seems large enough for a library if we are only checking the version of the charm, not workload.

2022-02-15 22:37 UTC, pengale commented
Versions as far as charms are concerned are complicated, and I'm not sure that we can demonstrate that this is the "correct" approach to integrating them into the core Operator Framework, especially given some of the inconsistencies in how the various tools involved record the charm version.

That's why I suggested using a library. Charm libraries are meant to be lightweight enough to address specific issues like "I want to know the revision number of the running charm". And if the library ends up getting used broadly, then that's a good argument for incorporating that particular feature into the core framework.

2022-02-16 16:00 UTC, sed-i commented
Just "revision" might be insufficient information:
When you `juju refresh --path` multiple times, revision is incremented:
```
App                    Version  Status  Scale  Charm                  Store     Channel  Rev  OS          Address         Message
alertmanager                    active      1  alertmanager-k8s       charmhub  edge       9  kubernetes  10.152.183.72
cos-configuration-k8s           active      1  cos-configuration-k8s  local                2  kubernetes  10.152.183.156
```
So after enough times you `juju refresh --path`, the revision number may reach/exceed the ch number, and knowing the origin ("store") as well becomes important.

2022-02-16 18:02 UTC, jnsgruk commented
Hmm, I can see why having access to the deployed revision might be useful in some cases - but it shouldn't be accessible through `CharmMeta` imo - because it isn't charm metadata, it's a run time concern

2022-02-16 19:59 UTC, rbarry82 commented
> Just "revision" might be insufficient information: When you `juju refresh --path` multiple times, revision is incremented:
> 
> ```
> App                    Version  Status  Scale  Charm                  Store     Channel  Rev  OS          Address         Message
> alertmanager                    active      1  alertmanager-k8s       charmhub  edge       9  kubernetes  10.152.183.72
> cos-configuration-k8s           active      1  cos-configuration-k8s  local                2  kubernetes  10.152.183.156
> ```
>
> So after enough times you `juju refresh --path`, the revision number may reach/exceed the ch number, and knowing the origin ("store") as well becomes important.

I tested this, and it doesn't appear to be reproducible if you're using charms from charmhub (not only can you not `juju refresh` if you're running the latest version, but `revision` is predictable). 

Repeatedly refreshing from a local `.charm` file and going past the released version in Charmhub is a possible edge case, but also seems to be a development workflow which is not in scope unless OF also exposed the rest of the information in `juju status foo --format=json` (such as the store/etc), which is substantially larger.

In addition, `revision` is, as @jnsgruk noted, "runtime" information, since the file is present locally and there's no need to go query the controller or reach "outside". It can be read in/parsed with essentially zero runtime cost or external dependencies.

> Hmm, I can see why having access to the deployed revision might be useful in some cases - but it shouldn't be accessible through `CharmMeta` imo - because it isn't charm metadata, it's a run time concern

Exposing it as a property on `CharmBase` is equally plausible. I wrote the PR adding it to `CharmMeta` to leave it as, essentially, "extra" information which could be peeked into if desired, but with an API which would be stable even if it's added to `CharmBase`, some `RevisionMapping` in `Model`, or other location later. I think that _where_ it is exposed is far less important to consumers than whether it is or not.

I'll drop `version` out until when/if `charmcraft` adds automatic versions back

2022-02-17 13:27 UTC, jameinel commented
We'll need to be careful about 'revision' because I'm pretty sure the value in the file is actually 99% of the time wrong. It was originally used when publishing to the charm store, and the store would actually rewrite that file as part of the upload.

With Charmhub, the policy was that the store does *not* rewrite anything, it just takes blobs. And so there is no way (unless Juju starts rewriting it at unpack time) for it to contain the correct value. Especially when it comes to the series/arch changes, so every blob uploaded now gets a new revision that you wouldn't know in advance when building the blob. 
(As I understand it, the original goal of tracking revision in a file was so that if you downloaded the charm you would have an idea of what content you had, but if the store isn't keeping that up to date, it becomes irrelevant. We *could* have Juju update that content when unpacking a charm for a unit, but I'd like to have a strong understanding of why we want it, because there are lots of ways that *revision* is a very weak identifier.)

As noted, every local upload is a new revision, whether or not it is new content. Juju does track the revision from the store and puts it into status, but it does *not* end up in the revision file. (I just confirmed that deploying ch:jameinel-ubuntu-lite shows up as revision 10 in `juju status` but has a revision file with '0' as the only content.)

Version I'm still quite keen on getting working on all the systems as a human-readable replacement for revision. As version is designed as an identifier from some other system, it can be put into the build process. (whether it was human assigned as part of a release process, or assigned from a git repo, etc.)
Which is what makes c5102a7 odd, in that it seems to double down on revision in place of version, while I would recommend the opposite.

2022-02-17 14:48 UTC, sed-i commented
> [local charm] shows up as revision 10 in juju status but has a revision file with '0' as the only content

That's good because with this in place at least there can be no confusion between ch content (non zero revision) and dev content (always zero revision).

2022-02-17 16:30 UTC, jameinel commented
I think you interpreted that backwards. The content of 'revision' was 0
when deployed from charmhub.

On Thu, Feb 17, 2022 at 9:48 AM Leon ***@***.***> wrote:

> [local charm] shows up as revision 10 in juju status but has a revision
> file with '0' as the only content
>
> That's good because with this in place at least there can be no confusion
> between ch content (non zero revision) and dev content (always zero
> revision).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/canonical/operator/pull/692#issuecomment-1043029164>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABRQ7JZYISBYZXSDNKCBGTU3UDE7ANCNFSM5ONIGGUA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-17 23:35 UTC, rbarry82 commented
> We'll need to be careful about 'revision' because I'm pretty sure the value in the file is actually 99% of the time wrong. It was originally used when publishing to the charm store, and the store would actually rewrite that file as part of the upload.
> 
> With Charmhub, the policy was that the store does _not_ rewrite anything, it just takes blobs. And so there is no way (unless Juju starts rewriting it at unpack time) for it to contain the correct value. Especially when it comes to the series/arch changes, so every blob uploaded now gets a new revision that you wouldn't know in advance when building the blob. (As I understand it, the original goal of tracking revision in a file was so that if you downloaded the charm you would have an idea of what content you had, but if the store isn't keeping that up to date, it becomes irrelevant. We _could_ have Juju update that content when unpacking a charm for a unit, but I'd like to have a strong understanding of why we want it, because there are lots of ways that _revision_ is a very weak identifier.)
> 
> As noted, every local upload is a new revision, whether or not it is new content. Juju does track the revision from the store and puts it into status, but it does _not_ end up in the revision file. (I just confirmed that deploying ch:jameinel-ubuntu-lite shows up as revision 10 in `juju status` but has a revision file with '0' as the only content.)

The plot thickens.

I double checked this with a charm from charmhub, and you're right -- `revision` doesn't match the revision on the store or what `juju status` reports, though it _does_ have a `revision` present (which wasn't there at build time).

Considering that local charms never uploaded to the store also have `revision` set (and it's not in the `.charm` file), it certainly appears to be [written directly by Juju](https://github.com/juju/juju/blob/efcf4c6acfb41c6eeb01f9f03cb96c4b3a507a04/apiserver/charms.go#L408), which should be able to get the correct information from the store revision, right?

I agree that revision is a very weak identifier -- even weaker than I originally thought, but a weak identifier is better than _no_ identifier.

> 
> Version I'm still quite keen on getting working on all the systems as a human-readable replacement for revision. As version is designed as an identifier from some other system, it can be put into the build process. (whether it was human assigned as part of a release process, or assigned from a git repo, etc.) Which is what makes [c5102a7](https://github.com/canonical/operator/commit/c5102a7ed6993c5bdd81897971b93c32a181560c) odd, in that it seems to double down on revision in place of version, while I would recommend the opposite.

The comments above this in the PR address the muddy history around `version` (the once and future identifier), but it was dropped from this PR since there's not a consistent story around it.

Then again, there doesn't seem to be a consistent story around `revision` either, except "it's present".

2022-03-01 22:10 UTC, rwcarlsen commented
It sounds like there are no consistent artifacts for the ops framework to present.  I'm inclined to not give charmers a broken crutch and wait until the dust settles on resolving this e.g. https://github.com/canonical/charmcraft/issues/37

2022-03-07 18:23 UTC, closed without merging