Added EventBase-subclass check that snapshot/restore have been overridden if new attrs have been added
canonical/operator pull request #770
Opened 2022-06-07 09:15 UTC by PietroPasotti

## Please provide the following details to expedite review (and delete this heading)
Users often forget to override `snapshot/restore` when they subclass EventBase and add some instance attributes. This can be hard to debug.
The proposed solution here is to add a subclass-instantiation-time-check that verifies that if new instance attributes are present, then `snapshot/restore` have been overridden.

## Checklist

 - [x] Have any types changed? If so, have the type annotations been updated?
 - [ ] If this code exposes model data, does it do so thoughtfully, in a way that aids understanding?
 - [x] Do error messages, if any, present charm authors or operators with enough information to solve the problem?

## QA steps

Added unittests in test_framework.py

## Documentation changes

We should add to the documentation that you will get a warning if you forget to override the methods.

## Bug reference

Fixes #769 

## Changelog

- Adds runtime warning if user forgot to override `EventBase.snapshot/restore`.

2022-06-07 15:53 UTC, rwcarlsen reviewed
Perhaps a check at snapshot time that compares the snapshot attribs to the class instance attribs would be more reliable.  Because it's very possible to already have an override, but forget to include a newly added attribute.  And a similar check could occur for restore.

2022-06-08 05:48 UTC, PietroPasotti commented
> Perhaps a check at snapshot time that compares the snapshot attribs to the class instance attribs would be more reliable. Because it's very possible to already have an override, but forget to include a newly added attribute. And a similar check could occur for restore.

The risk there is renaming: nothing forbids the user to add a `_number` attribute but snapshot it as `number`. I don't think we can solve that problem.

If we want a more reliable workaround we need to rewrite how events are defined.

2022-06-08 05:50 UTC, PietroPasotti commented
> > Perhaps a check at snapshot time that compares the snapshot attribs to the class instance attribs would be more reliable. Because it's very possible to already have an override, but forget to include a newly added attribute. And a similar check could occur for restore.
> 
> The risk there is renaming: nothing forbids the user to add a `_number` attribute but snapshot it as `number`. I don't think we can solve that problem.
> 
> If we want a more reliable workaround we need to rewrite how events are defined.

The present solution also doesn't prevent the user from subclassing once, overriding snapshot/restore, then subclass once again (add some attrs) and forget override again.
I know it's not perfect, the question is: is it good enough to be useful in *enough* cases?

2022-06-08 21:46 UTC, rwcarlsen commented
One idea discussed was the idea of round-tripping event data through snapshot->restore->snapshot->restore and comparing results in order to ensure snapshot and restore are implemented consistently with each other.  You could potentially use this approach to compare the resulting event object's attributes with the original's to see if snapshot/restore aren't missing any fields, but then you'd need a way to discriminate between fields that _should_ be snapshotted vs. not - in case a custom event had any ephemeral fields not intended to be persisted.

2022-06-09 15:09 UTC, pengale requested changes
As I mentioned in the standup, I think that there are a significant number of cases where charm authors want to add values that are loaded in from the environment, rather than stored and restored.

This makes that pattern harder. I'm open to more and different ideas along these lines, though. That stored object is a big potential gotcha.

2022-06-09 15:42 UTC, rwcarlsen commented
I agree.  The double round-tripping skirts that problem, but gives you a weaker guarantee.  The single round-trip will give false-positive errors  unless you can come up with some way to determine which fields you should check vs ignore.

2022-06-23 10:34 UTC, jnsgruk commented
Feels like this one can be closed out? More thinking required it seems.

2022-06-23 12:30 UTC, closed without merging