Action stdout results
canonical/operator pull request #809
Opened 2022-08-03 13:46 UTC by PietroPasotti

Stderr output emitted during an action hook execution gets injected in an action's results by juju.
- documented this in the ActionEvent docstring
- added a check that users don't manually set_results to anything containing "Stdout", because it will either be overridden or override juju's or break something, not sure which one but either way, it ain't good.

## Checklist
 - [x] Do error messages, if any, present charm authors or operators with enough information to solve the problem?

## QA steps

Added test for the new error condition.

## Documentation changes

We should make this clear in the ActionEvent-related documentation.

## Changelog

*Please include a bulleted list of items here, suitable for inclusion in a release changelog.*

- Added check that `ActionEvent.set_results` will fail if the results contain the 'special' juju key "Stdout"

2022-08-03 19:42 UTC, rwcarlsen commented
Ha! - I actually fixed a bug in juju a while back related to this: https://github.com/juju/juju/pull/13748 - action-set should give you an error now (in new enough versions of juju).  So we don't need our own framework error, but possibly a framework-level error can be "nicer".

2022-08-04 11:59 UTC, PietroPasotti commented
> Ha! - I actually fixed a bug in juju a while back related to this: [juju/juju#13748](https://github.com/juju/juju/pull/13748) - action-set should give you an error now (in new enough versions of juju). So we don't need our own framework error, but possibly a framework-level error can be "nicer".

Right, I still think it's best to raise our own error instead to wait for juju to error out.

2022-08-04 14:48 UTC, rwcarlsen requested changes
Here are the known "special" keys: "stdout", "stdout-encoding", "stderr", "stderr-encoding". Let's check for those as well.

2022-08-08 12:02 UTC, PietroPasotti commented
> Here are the known "special" keys: "stdout", "stdout-encoding", "stderr", "stderr-encoding". Let's check for those as well.
I found the [juju source where the keys are being defined/used](https://github.com/juju/juju/blob/fd886a18e169e4741f557d6b574bba06ff0b190d/worker/uniter/runner/runner.go#L329), but there is an issue: 
![image](https://user-images.githubusercontent.com/6230162/183413156-bd2489c9-cbfd-49fd-90e6-7260eadb2b9b.png)
"Stderr" seems to be capitalized in this sample output. I don't see in the juju code where this capitalization is done, I'm wondering if it's an artifact from the juju client displaying the action results, rather than juju itself. It is suspicious that `admin-password` is not capitalized, however.
Should I include the capitalized or the non-capitalized version of "stdout" in the 'reserved' keys? 
And what about the other keys? Is it `Stdout-encoding` or `Stdout-Encoding`, or...?

2022-08-08 13:02 UTC, juanmanuel-tirado commented
In 2.9 there is a piece of code that changes these keys to start with uppercase when running into compat mode. Check [here](https://github.com/juju/juju/blob/5f82824fc0e87316d48683949e82a0414b3cf0ce/cmd/juju/action/showoutput.go#L416). This has been changed in 3.0 [here](https://github.com/juju/juju/blob/0ffacc32b7bb871879695b1c4515047a09399fd0/cmd/juju/action/common.go#L694)

2022-08-08 13:46 UTC, PietroPasotti commented
> 

Thanks! From reading that code it seems that ReturnCode is also a reserved key.

2022-08-08 13:57 UTC, PietroPasotti commented
I just noticed that the regex we use to validate the action result key `'^[a-z0-9](([a-z0-9-.]+)?[a-z0-9])?$'`actually precludes using uppercase letters altogether. This was added I think by @jnsgruk. 
Is the regex too strict, or were you aware of these issues and took a different solution, or something else..?

2022-08-08 14:53 UTC, jnsgruk commented
> I just noticed that the regex we use to validate the action result key `'^[a-z0-9](([a-z0-9-.]+)?[a-z0-9])?$'`actually precludes using uppercase letters altogether. This was added I think by @jnsgruk. Is the regex too strict, or were you aware of these issues and took a different solution, or something else..?

Interesting. Pretty sure a based the regex off something that lives in the Juju codebase (I can check a bit later if no one beats me to it!)

2022-08-08 19:10 UTC, rwcarlsen commented
Do the juju checks need to be updated to check for ReturnCode (in addition to the stderr/out, etc.)?

2022-08-09 08:03 UTC, PietroPasotti commented
> 

Do you mean the code on the juju side?

2022-08-09 09:23 UTC, jnsgruk commented
> I just noticed that the regex we use to validate the action result key `'^[a-z0-9](([a-z0-9-.]+)?[a-z0-9])?$'`actually precludes using uppercase letters altogether. This was added I think by @jnsgruk. Is the regex too strict, or were you aware of these issues and took a different solution, or something else..?

Here it is: https://github.com/juju/juju/blob/137a772ed339b73b856e9adc0a5624976c2890b2/worker/uniter/runner/jujuc/action-set.go#L85

The `action-set` command validates that keys start with lowercase letters, so that's why the regex is as such in `ops` :)

2022-08-09 11:39 UTC, PietroPasotti commented
Allright, so it seems that for now we're in the clear -- attempting to set Stdout/Stderr/ReturnCode and company will result into an error, not because they're 'protected keys', but because they contain uppercase characters.
I'll reshape this PR to only include documentation changes.

2022-08-09 13:42 UTC, rwcarlsen commented
When I last dealt with this trying to solve https://github.com/canonical/operator/issues/689 - somewhere in juju, the lower-case-key names were still being clobbered by the CamelCase special ones (e.g. results "stdout" was clobbered by juju's special "Stdout").

2022-08-30 17:36 UTC, pengale reviewed
It's not clear to me where we're guarding against manually adding a Stdout key here. Did I miss something? (If so, a friendly comment inline would be appreciated.)

2022-08-30 20:54 UTC, rwcarlsen commented
I think the conclusion was that checks in juju should cover the relevant clobbering concerns.  So this PR is just doc clarifications and such.

2022-10-04 12:26 UTC, merged