Fix incorrect kwarg handling in testing backend storage_list
canonical/operator pull request #820
Opened 2022-08-24 16:30 UTC by rwcarlsen

storage_list in the testing backend was erroneously using "all" instead
of "include_detached" - in its list comprehension to accumulate
active/attached storage entries.  We didn't get an error before since
"all" is a python builtin :-/  Correcting this also unveiled another
error where we weren't invalidating the stale storages list/cache in the
model when attaching a new storage - which showed up as failed snapshot
loading for storage events.  The cache invalidation code was moved from
Harness.add_storage to Harness.attach_storage where it belongs.

Fixes #819

## Please provide the following details to expedite review (and delete this heading)

*Replace with a description about why this change is needed, along with a description of what changed.*

## Checklist

 - [ ] Have any types changed? If so, have the type annotations been updated?
 - [ ] If this code exposes model data, does it do so thoughtfully, in a way that aids understanding?

       We want to avoid simple passthrough of model data, without contextualization, where possible.

 - [ ] Do error messages, if any, present charm authors or operators with enough information to solve the problem?

## QA steps

*Please replace with how we can verify that the change works.*

```sh
QA steps here
```

## Documentation changes

*Please replace with any notes about how it affects current user workflow, CLI, or API.*

## Bug reference

*Please add a link to any bugs that this change is related to, e.g., https://bugs.launchpad.net/juju/+bug/9876543*

## Changelog

*Please include a bulleted list of items here, suitable for inclusion in a release changelog.*

- *Adds feature foo, which allows charm authors to ...*
- *Fixes bug bar, which means that operators no longer need workaround qux ...*

2022-08-25 06:25 UTC, PietroPasotti requested changes
The main reason why that rename didn't raise any red flags is that we didn't have a single test using the `include_detached` kwarg.
I think we should add some to catch regressions.

2022-08-25 15:42 UTC, rwcarlsen commented
Yeah - That's a good idea.  I'll get something added in.

2022-08-25 19:36 UTC, rwcarlsen commented
@PietroPasotti - added a test. This should be ready for a final look.

2022-08-25 21:05 UTC, jnsgruk approved these changes
LGTM, thanks.

2022-08-26 05:50 UTC, PietroPasotti requested changes
What I meant is, a test that **uses** the include_detached kwarg, to cover that path as well.
Your test looks good, but it misses something like:

```
self.assertEqual(len(harness.model.backend.storage_list('test'), 0)
self.assertEqual(len(harness.model.backend.storage_list('test', include_detached), 1)
```

2022-08-26 15:36 UTC, rwcarlsen commented
But that is sort of testing internal/private APIs - which is useful sometimes.  But in this case we have a relatively straight-forward way to test the public API behavior that we want that covers the previously broken behavior of that internal API.  If we change the name of that param in the future, for example, the test I added won't break, but one like you suggested would need to be "fixed".

2022-08-29 07:52 UTC, PietroPasotti approved these changes

2022-08-29 07:52 UTC, PietroPasotti commented
Pardon, didn't realize the test you added made use of that path. You make a valid point :)

2022-08-30 08:25 UTC, merged