Remove check for existing event on define_event
canonical/operator pull request #824
Opened 2022-09-05 04:33 UTC by samuelallan72

This check feels arbitrary, and causes issues in cases where
code that defines an event is somehow unavoidable called more than once.

This check was originally introduced in 41b8081,
without an explanation of why it was a bad thing
for an event to override an existing event.

## Checklist

 - [x] (no change) Have any types changed? If so, have the type annotations been updated?
 - [x] (no change) If this code exposes model data, does it do so thoughtfully, in a way that aids understanding?

       We want to avoid simple passthrough of model data, without contextualization, where possible.

 - [x] (na) Do error messages, if any, present charm authors or operators with enough information to solve the problem?

## QA steps

Unit test updates are included, but the general gist is:

1. try to define an event with the same name as an already defined event
2. verify that there are no raised errors, and that the new event has replaced the old event

## Documentation changes

docstrings updated

## Bug reference

Motivation for this pull request: https://review.opendev.org/c/openstack/charm-ops-sunbeam/+/855308/comments/d1e6dbf8_02df450a

## Changelog

- `define_event` no longer raises an error on overriding existing events.

2022-09-07 14:00 UTC, pengale requested changes
Thank you for the contribution! 

That said ... it would be a bad idea to remove the check.

Ops uses a labeling system to track and reconstruct events between hook executions (each time a hook runs, the Juju Agent invokes a fresh instance of ops -- there is no ops process that persists on the host between hooks). Having duplicate Python objects creates duplicate labels, which increases the risk of ops running the "wrong" code after something has been deferred.

Absent a test demonstrating that my concerns above are overblown, I'm going to give this a -1.

2022-09-07 14:44 UTC, pengale commented
Had a conversation about this during the sync.

@PietroPasotti, would you sync up with @swalladge on this? I think that we may be able to offer an alternate workaround, but we need to understand what you're doing in your tests in order to understand what we can to do fix it. :-)

2022-09-08 15:18 UTC, pengale commented
> Can I just point out that this kind of explanation would have been excellent as a comment next to the check in `define_event` and/or in the description of the PR that introduced the check. Often the "why" is missing from these things until someone tries to remove it.

Oh I agree! The lack of documentation in some of the core bits of ops is a source of pain for the people currently working on it. I think that updating the inline comments is part of the work that we need to do here.

2022-09-08 22:32 UTC, closed without merging

2022-09-09 17:11 UTC, rwcarlsen commented
Agree - either that or some sort of instance attribute evolution (which may or may not be possible given various ops shenanicans :/ )

2022-09-13 07:49 UTC, nishant-dash commented
As suggested by @PietroPasotti, I will pick up remedying the documentation for  [framework.py](https://github.com/canonical/operator/blob/41b808145b2b3b58cc2efc98c6e5a4de2d031aef/juju/framework.py) by adding the points mentioned by @pengale to `define_event`.